### PR TITLE
#51 delete on messages

### PR DESCRIPTION
**Pull request by isaacdarcilla**
Added swipe delete on messages

### CODE REVIEW

**Comment by joshxfi** [comment]
@isaacdarcilla I'm getting this error: `TouchEvent not defined`
here''s what I found: https://stackoverflow.com/questions/27313488/touchevent-not-working-in-firefox-and-other-website-browser

PS: I'm using firefox

image

**Comment by isaacdarcilla** [comment]
> 

Let me check

**Comment by isaacdarcilla** [comment]
Can't login due to captcha
image

**Comment by joshxfi** [comment]
@isaacdarcilla we converted the repo into a monorepo so there will be conflicts, the nextjs project is at `apps/web`

**Comment by joshxfi** [comment]
added this for now https://github.com/joshxfi/umamin/pull/94 , we can use the slide type delete on our upcoming mobile app

image

**Pull request closed without merging**
